class Performatives:
    INFORM_WORK_COMPLETED = "InformWorkCompleted"
    REQUEST_GRANT_ACCESS_TO_CLIENT = "RequestGrantAccessToClient"
    CONFIRM_ACCESS_GRANTED_TO_CLIENT = "ConfirmAccessGrantedToClient"
    CONFIRM_ACCESS_GRANTED = "ConfirmAccessGranted"
    PROPOSE_DATETIME = "DatetimeProposal"
    REQUEST_USER_AUTHENTICATION = "UserAuthentication"
    INFORM_USER_ABSENCE = "InformUserAbsence"
    USER_PAYMENT_INITIAL = "RequestPaymentInitial"
    USER_PENALTIES_VERIFICATION = "RequestPenaltiesVerification"
    USER_AUTHENTICATION_ACCEPTED = "InformAuthenticationAccepted"
    USER_AUTHENTICATION_REJECTED = "InformAuthenticationRejected"
    USER_PAYMENT_ACCEPTED = "InformPaymentAccepted"
    USER_PAYMENT_REJECTED = "InformPaymentRejected"
    USER_PENALTIES_VERIFICATION_ACCEPTED = "InformPenaltiesVerificationAccepted"
    USER_PENALTIES_VERIFICATION_REJECTED = "InformPenaltiesVerificationRejected"
    DATE_ACCEPTED = "InformDateAccepted"
    DATE_REJECTED = "InformDateRejected"
    RESERVATION_CHECK_RESPONSE_ACCEPTED = "InformReservationCheckAccepted"
    RESERVATION_CHECK_RESPONSE_REJECTED = "InformReservationCheckRejected"
    RESERVATION_CHECK = "RequestReservationCheck"
    # TODO zmienić nazwy na bardziej FIPA tych poniżej
    ABSENCES = "Absences"
