class Performatives:
    INFORM_WORK_COMPLETED = "InformWorkCompleted"
    REQUEST_GRANT_ACCESS_TO_CLIENT = "RequestGrantAccessToClient"
    CONFIRM_ACCESS_GRANTED_TO_CLIENT = "ConfirmAccessGrantedToClient"
    CONFIRM_ACCESS_GRANTED = "ConfirmAccessGranted"
    PROPOSE_DATETIME = "DatetimeProposal"
    REQUEST_USER_AUTHENTICATION = "UserAuthentication"
    INFORM_USER_ABSENCE = "InformUserAbsence"
# TODO zmienić nazwy na bardziej FIPA tych poniżej
    USER_PAYMENT_INITIAL = "UserPaymentInitial"
    USER_PENALTIES_VERIFICATION = "UserPenaltiesVerification"
    USER_AUTHENTICATION_ACCEPTED = "UserAuthenticationAccepted"
    USER_AUTHENTICATION_REJECTED = "UserAuthenticationRejected"
    USER_PAYMENT_ACCEPTED = "UserPaymentAccepted"
    USER_PAYMENT_REJECTED = "UserPaymentRejected"
    USER_PENALTIES_VERIFICATION_ACCEPTED = "UserPenaltiesVerificationAccepted"
    USER_PENALTIES_VERIFICATION_REJECTED = "UserPenaltiesVerificationRejected"
    DATE_ACCEPTED = "DateAccepted"
    DATE_REJECTED = "DateRejected"
    ABSENCES = "Absences"
    RESERVATION_CHECK = "ReservationCheck"
    RESERVATION_CHECK_RESPONSE_ACCEPTED = "ReservationCheckResponseAccepted"
    RESERVATION_CHECK_RESPONSE_REJECTED = "ReservationCheckResponseRejected"
